version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=2005
      - PG_URL=postgres://postgres:2005@postgres:5432/postgres?sslmode=disable
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    depends_on:
      - mongo
      - redis
    networks:
      - finance

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:2005@postgresdb:5432/postgres?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-db-data:/data/db
    networks:
      - finance

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - finance

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9006:9006"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
    networks:
      - finance

volumes:
  mongo-db-data:
  migrations:

networks:
  finance:
